//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;

//namespace TwitterLibrary
//{
//    class TwitterModel2
//    {
//    }
//}
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using JsonCSharpClassGenerator;
using Newtonsoft.Json;

namespace TwitterLibrary
{

    public class Description
    {
        private JObject __jobject;
        public Description(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<object> _urls;
        public IList<object> Urls
        {
            get
            {
                if (_urls == null)
                    _urls = (IList<object>)JsonClassHelper.ReadArray<object>(JsonClassHelper.GetJToken<JArray>(__jobject, "urls"), JsonClassHelper.ReadObject, typeof(IList<object>));
                return _urls;
            }
        }

    }

    public class Entities
    {
        private JObject __jobject;
        public Entities(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Description _description;
        public Description Description
        {
            get
            {
                if (_description == null)
                    _description = JsonClassHelper.ReadStronglyTypedObject<Description>(JsonClassHelper.GetJToken<JObject>(__jobject, "description"));
                return _description;
            }
        }

    }

    public class User
    {
        private JObject __jobject;
        public User(JObject obj)
        {
            this.__jobject = obj;
        }

        public int Id
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "id"));
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        public string Name
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "name"));
            }
        }

        public string ScreenName
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "screen_name"));
            }
        }

        public string Location
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "location"));
            }
        }

        public object ProfileLocation
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "profile_location"));
            }
        }

        public string Description
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "description"));
            }
        }

        public object Url
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "url"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Entities _entities;
        public Entities Entities
        {
            get
            {
                if (_entities == null)
                    _entities = JsonClassHelper.ReadStronglyTypedObject<Entities>(JsonClassHelper.GetJToken<JObject>(__jobject, "entities"));
                return _entities;
            }
        }

        public bool Protected
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "protected"));
            }
        }

        public int FollowersCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "followers_count"));
            }
        }

        public int FriendsCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "friends_count"));
            }
        }

        public int ListedCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "listed_count"));
            }
        }

        public string CreatedAt
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "created_at"));
            }
        }

        public int FavouritesCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "favourites_count"));
            }
        }

        public int UtcOffset
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "utc_offset"));
            }
        }

        public string TimeZone
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "time_zone"));
            }
        }

        public bool GeoEnabled
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "geo_enabled"));
            }
        }

        public bool Verified
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "verified"));
            }
        }

        public int StatusesCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "statuses_count"));
            }
        }

        public string Lang
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "lang"));
            }
        }

        public bool ContributorsEnabled
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "contributors_enabled"));
            }
        }

        public bool IsTranslator
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "is_translator"));
            }
        }

        public bool IsTranslationEnabled
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "is_translation_enabled"));
            }
        }

        public string ProfileBackgroundColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_background_color"));
            }
        }

        public string ProfileBackgroundImageUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_background_image_url"));
            }
        }

        public string ProfileBackgroundImageUrlHttps
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_background_image_url_https"));
            }
        }

        public bool ProfileBackgroundTile
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_background_tile"));
            }
        }

        public string ProfileImageUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_image_url"));
            }
        }

        public string ProfileImageUrlHttps
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_image_url_https"));
            }
        }

        public string ProfileBannerUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_banner_url"));
            }
        }

        public string ProfileLinkColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_link_color"));
            }
        }

        public string ProfileSidebarBorderColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_sidebar_border_color"));
            }
        }

        public string ProfileSidebarFillColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_sidebar_fill_color"));
            }
        }

        public string ProfileTextColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_text_color"));
            }
        }

        public bool ProfileUseBackgroundImage
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_use_background_image"));
            }
        }

        public bool DefaultProfile
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "default_profile"));
            }
        }

        public bool DefaultProfileImage
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "default_profile_image"));
            }
        }

        public bool Following
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "following"));
            }
        }

        public bool FollowRequestSent
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "follow_request_sent"));
            }
        }

        public bool Notifications
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "notifications"));
            }
        }

    }

    public class Hashtag
    {
        private JObject __jobject;
        public Hashtag(JObject obj)
        {
            this.__jobject = obj;
        }

        public string Text
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "text"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

    }

    public class UserMention
    {
        private JObject __jobject;
        public UserMention(JObject obj)
        {
            this.__jobject = obj;
        }

        public string ScreenName
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "screen_name"));
            }
        }

        public string Name
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "name"));
            }
        }

        public int Id
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "id"));
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

    }

    public class Url
    {
        private JObject __jobject;
        public Url(JObject obj)
        {
            this.__jobject = obj;
        }

        public string Url
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "url"));
            }
        }

        public string ExpandedUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "expanded_url"));
            }
        }

        public string DisplayUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "display_url"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

    }

    public class Thumb
    {
        private JObject __jobject;
        public Thumb(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Small
    {
        private JObject __jobject;
        public Small(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Large
    {
        private JObject __jobject;
        public Large(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Medium2
    {
        private JObject __jobject;
        public Medium2(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Sizes
    {
        private JObject __jobject;
        public Sizes(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Thumb _thumb;
        public Thumb Thumb
        {
            get
            {
                if (_thumb == null)
                    _thumb = JsonClassHelper.ReadStronglyTypedObject<Thumb>(JsonClassHelper.GetJToken<JObject>(__jobject, "thumb"));
                return _thumb;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Small _small;
        public Small Small
        {
            get
            {
                if (_small == null)
                    _small = JsonClassHelper.ReadStronglyTypedObject<Small>(JsonClassHelper.GetJToken<JObject>(__jobject, "small"));
                return _small;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Large _large;
        public Large Large
        {
            get
            {
                if (_large == null)
                    _large = JsonClassHelper.ReadStronglyTypedObject<Large>(JsonClassHelper.GetJToken<JObject>(__jobject, "large"));
                return _large;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Medium2 _medium;
        public Medium2 Medium
        {
            get
            {
                if (_medium == null)
                    _medium = JsonClassHelper.ReadStronglyTypedObject<Medium2>(JsonClassHelper.GetJToken<JObject>(__jobject, "medium"));
                return _medium;
            }
        }

    }

    public class Medium
    {
        private JObject __jobject;
        public Medium(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private object _id;
        public object Id
        {
            get
            {
                if (_id == null)
                    _id = JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "id"));
                return _id;
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

        public string MediaUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "media_url"));
            }
        }

        public string MediaUrlHttps
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "media_url_https"));
            }
        }

        public string Url
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "url"));
            }
        }

        public string DisplayUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "display_url"));
            }
        }

        public string ExpandedUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "expanded_url"));
            }
        }

        public string Type
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "type"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Sizes _sizes;
        public Sizes Sizes
        {
            get
            {
                if (_sizes == null)
                    _sizes = JsonClassHelper.ReadStronglyTypedObject<Sizes>(JsonClassHelper.GetJToken<JObject>(__jobject, "sizes"));
                return _sizes;
            }
        }

        public long? SourceStatusId
        {
            get
            {
                return JsonClassHelper.ReadNullableLong(JsonClassHelper.GetJToken<JValue>(__jobject, "source_status_id"));
            }
        }

        public string SourceStatusIdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "source_status_id_str"));
            }
        }

    }

    public class Entities2
    {
        private JObject __jobject;
        public Entities2(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Hashtag> _hashtags;
        public IList<Hashtag> Hashtags
        {
            get
            {
                if (_hashtags == null)
                    _hashtags = (IList<Hashtag>)JsonClassHelper.ReadArray<Hashtag>(JsonClassHelper.GetJToken<JArray>(__jobject, "hashtags"), JsonClassHelper.ReadStronglyTypedObject<Hashtag>, typeof(IList<Hashtag>));
                return _hashtags;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<object> _symbols;
        public IList<object> Symbols
        {
            get
            {
                if (_symbols == null)
                    _symbols = (IList<object>)JsonClassHelper.ReadArray<object>(JsonClassHelper.GetJToken<JArray>(__jobject, "symbols"), JsonClassHelper.ReadObject, typeof(IList<object>));
                return _symbols;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<UserMention> _userMentions;
        public IList<UserMention> UserMentions
        {
            get
            {
                if (_userMentions == null)
                    _userMentions = (IList<UserMention>)JsonClassHelper.ReadArray<UserMention>(JsonClassHelper.GetJToken<JArray>(__jobject, "user_mentions"), JsonClassHelper.ReadStronglyTypedObject<UserMention>, typeof(IList<UserMention>));
                return _userMentions;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Url> _urls;
        public IList<Url> Urls
        {
            get
            {
                if (_urls == null)
                    _urls = (IList<Url>)JsonClassHelper.ReadArray<Url>(JsonClassHelper.GetJToken<JArray>(__jobject, "urls"), JsonClassHelper.ReadStronglyTypedObject<Url>, typeof(IList<Url>));
                return _urls;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Medium> _media;
        public IList<Medium> Media
        {
            get
            {
                if (_media == null)
                    _media = (IList<Medium>)JsonClassHelper.ReadArray<Medium>(JsonClassHelper.GetJToken<JArray>(__jobject, "media"), JsonClassHelper.ReadStronglyTypedObject<Medium>, typeof(IList<Medium>));
                return _media;
            }
        }

    }

    public class Url3
    {
        private JObject __jobject;
        public Url3(JObject obj)
        {
            this.__jobject = obj;
        }

        public string Url
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "url"));
            }
        }

        public string ExpandedUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "expanded_url"));
            }
        }

        public string DisplayUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "display_url"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

    }

    public class Url2
    {
        private JObject __jobject;
        public Url2(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Url3> _urls;
        public IList<Url3> Urls
        {
            get
            {
                if (_urls == null)
                    _urls = (IList<Url3>)JsonClassHelper.ReadArray<Url3>(JsonClassHelper.GetJToken<JArray>(__jobject, "urls"), JsonClassHelper.ReadStronglyTypedObject<Url3>, typeof(IList<Url3>));
                return _urls;
            }
        }

    }

    public class Url4
    {
        private JObject __jobject;
        public Url4(JObject obj)
        {
            this.__jobject = obj;
        }

        public string Url
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "url"));
            }
        }

        public string ExpandedUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "expanded_url"));
            }
        }

        public string DisplayUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "display_url"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

    }

    public class Description2
    {
        private JObject __jobject;
        public Description2(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Url4> _urls;
        public IList<Url4> Urls
        {
            get
            {
                if (_urls == null)
                    _urls = (IList<Url4>)JsonClassHelper.ReadArray<Url4>(JsonClassHelper.GetJToken<JArray>(__jobject, "urls"), JsonClassHelper.ReadStronglyTypedObject<Url4>, typeof(IList<Url4>));
                return _urls;
            }
        }

    }

    public class Entities3
    {
        private JObject __jobject;
        public Entities3(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Url2 _url;
        public Url2 Url
        {
            get
            {
                if (_url == null)
                    _url = JsonClassHelper.ReadStronglyTypedObject<Url2>(JsonClassHelper.GetJToken<JObject>(__jobject, "url"));
                return _url;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Description2 _description;
        public Description2 Description
        {
            get
            {
                if (_description == null)
                    _description = JsonClassHelper.ReadStronglyTypedObject<Description2>(JsonClassHelper.GetJToken<JObject>(__jobject, "description"));
                return _description;
            }
        }

    }

    public class User2
    {
        private JObject __jobject;
        public User2(JObject obj)
        {
            this.__jobject = obj;
        }

        public int Id
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "id"));
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        public string Name
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "name"));
            }
        }

        public string ScreenName
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "screen_name"));
            }
        }

        public string Location
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "location"));
            }
        }

        public object ProfileLocation
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "profile_location"));
            }
        }

        public string Description
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "description"));
            }
        }

        public string Url
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "url"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Entities3 _entities;
        public Entities3 Entities
        {
            get
            {
                if (_entities == null)
                    _entities = JsonClassHelper.ReadStronglyTypedObject<Entities3>(JsonClassHelper.GetJToken<JObject>(__jobject, "entities"));
                return _entities;
            }
        }

        public bool Protected
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "protected"));
            }
        }

        public int FollowersCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "followers_count"));
            }
        }

        public int FriendsCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "friends_count"));
            }
        }

        public int ListedCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "listed_count"));
            }
        }

        public string CreatedAt
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "created_at"));
            }
        }

        public int FavouritesCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "favourites_count"));
            }
        }

        public int? UtcOffset
        {
            get
            {
                return JsonClassHelper.ReadNullableInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "utc_offset"));
            }
        }

        public string TimeZone
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "time_zone"));
            }
        }

        public bool GeoEnabled
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "geo_enabled"));
            }
        }

        public bool Verified
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "verified"));
            }
        }

        public int StatusesCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "statuses_count"));
            }
        }

        public string Lang
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "lang"));
            }
        }

        public bool ContributorsEnabled
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "contributors_enabled"));
            }
        }

        public bool IsTranslator
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "is_translator"));
            }
        }

        public bool IsTranslationEnabled
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "is_translation_enabled"));
            }
        }

        public string ProfileBackgroundColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_background_color"));
            }
        }

        public string ProfileBackgroundImageUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_background_image_url"));
            }
        }

        public string ProfileBackgroundImageUrlHttps
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_background_image_url_https"));
            }
        }

        public bool ProfileBackgroundTile
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_background_tile"));
            }
        }

        public string ProfileImageUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_image_url"));
            }
        }

        public string ProfileImageUrlHttps
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_image_url_https"));
            }
        }

        public string ProfileBannerUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_banner_url"));
            }
        }

        public string ProfileLinkColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_link_color"));
            }
        }

        public string ProfileSidebarBorderColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_sidebar_border_color"));
            }
        }

        public string ProfileSidebarFillColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_sidebar_fill_color"));
            }
        }

        public string ProfileTextColor
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_text_color"));
            }
        }

        public bool ProfileUseBackgroundImage
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "profile_use_background_image"));
            }
        }

        public bool DefaultProfile
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "default_profile"));
            }
        }

        public bool DefaultProfileImage
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "default_profile_image"));
            }
        }

        public bool Following
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "following"));
            }
        }

        public bool FollowRequestSent
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "follow_request_sent"));
            }
        }

        public bool Notifications
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "notifications"));
            }
        }

    }

    public class Hashtag2
    {
        private JObject __jobject;
        public Hashtag2(JObject obj)
        {
            this.__jobject = obj;
        }

        public string Text
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "text"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

    }

    public class UserMention2
    {
        private JObject __jobject;
        public UserMention2(JObject obj)
        {
            this.__jobject = obj;
        }

        public string ScreenName
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "screen_name"));
            }
        }

        public string Name
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "name"));
            }
        }

        public int Id
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "id"));
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

    }

    public class Url5
    {
        private JObject __jobject;
        public Url5(JObject obj)
        {
            this.__jobject = obj;
        }

        public string Url
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "url"));
            }
        }

        public string ExpandedUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "expanded_url"));
            }
        }

        public string DisplayUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "display_url"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

    }

    public class Medium4
    {
        private JObject __jobject;
        public Medium4(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Thumb2
    {
        private JObject __jobject;
        public Thumb2(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Small2
    {
        private JObject __jobject;
        public Small2(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Large2
    {
        private JObject __jobject;
        public Large2(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Sizes2
    {
        private JObject __jobject;
        public Sizes2(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Medium4 _medium;
        public Medium4 Medium
        {
            get
            {
                if (_medium == null)
                    _medium = JsonClassHelper.ReadStronglyTypedObject<Medium4>(JsonClassHelper.GetJToken<JObject>(__jobject, "medium"));
                return _medium;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Thumb2 _thumb;
        public Thumb2 Thumb
        {
            get
            {
                if (_thumb == null)
                    _thumb = JsonClassHelper.ReadStronglyTypedObject<Thumb2>(JsonClassHelper.GetJToken<JObject>(__jobject, "thumb"));
                return _thumb;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Small2 _small;
        public Small2 Small
        {
            get
            {
                if (_small == null)
                    _small = JsonClassHelper.ReadStronglyTypedObject<Small2>(JsonClassHelper.GetJToken<JObject>(__jobject, "small"));
                return _small;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Large2 _large;
        public Large2 Large
        {
            get
            {
                if (_large == null)
                    _large = JsonClassHelper.ReadStronglyTypedObject<Large2>(JsonClassHelper.GetJToken<JObject>(__jobject, "large"));
                return _large;
            }
        }

    }

    public class Medium3
    {
        private JObject __jobject;
        public Medium3(JObject obj)
        {
            this.__jobject = obj;
        }

        public long Id
        {
            get
            {
                return JsonClassHelper.ReadLong(JsonClassHelper.GetJToken<JValue>(__jobject, "id"));
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

        public string MediaUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "media_url"));
            }
        }

        public string MediaUrlHttps
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "media_url_https"));
            }
        }

        public string Url
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "url"));
            }
        }

        public string DisplayUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "display_url"));
            }
        }

        public string ExpandedUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "expanded_url"));
            }
        }

        public string Type
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "type"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Sizes2 _sizes;
        public Sizes2 Sizes
        {
            get
            {
                if (_sizes == null)
                    _sizes = JsonClassHelper.ReadStronglyTypedObject<Sizes2>(JsonClassHelper.GetJToken<JObject>(__jobject, "sizes"));
                return _sizes;
            }
        }

    }

    public class Entities4
    {
        private JObject __jobject;
        public Entities4(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Hashtag2> _hashtags;
        public IList<Hashtag2> Hashtags
        {
            get
            {
                if (_hashtags == null)
                    _hashtags = (IList<Hashtag2>)JsonClassHelper.ReadArray<Hashtag2>(JsonClassHelper.GetJToken<JArray>(__jobject, "hashtags"), JsonClassHelper.ReadStronglyTypedObject<Hashtag2>, typeof(IList<Hashtag2>));
                return _hashtags;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<object> _symbols;
        public IList<object> Symbols
        {
            get
            {
                if (_symbols == null)
                    _symbols = (IList<object>)JsonClassHelper.ReadArray<object>(JsonClassHelper.GetJToken<JArray>(__jobject, "symbols"), JsonClassHelper.ReadObject, typeof(IList<object>));
                return _symbols;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<UserMention2> _userMentions;
        public IList<UserMention2> UserMentions
        {
            get
            {
                if (_userMentions == null)
                    _userMentions = (IList<UserMention2>)JsonClassHelper.ReadArray<UserMention2>(JsonClassHelper.GetJToken<JArray>(__jobject, "user_mentions"), JsonClassHelper.ReadStronglyTypedObject<UserMention2>, typeof(IList<UserMention2>));
                return _userMentions;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Url5> _urls;
        public IList<Url5> Urls
        {
            get
            {
                if (_urls == null)
                    _urls = (IList<Url5>)JsonClassHelper.ReadArray<Url5>(JsonClassHelper.GetJToken<JArray>(__jobject, "urls"), JsonClassHelper.ReadStronglyTypedObject<Url5>, typeof(IList<Url5>));
                return _urls;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Medium3> _media;
        public IList<Medium3> Media
        {
            get
            {
                if (_media == null)
                    _media = (IList<Medium3>)JsonClassHelper.ReadArray<Medium3>(JsonClassHelper.GetJToken<JArray>(__jobject, "media"), JsonClassHelper.ReadStronglyTypedObject<Medium3>, typeof(IList<Medium3>));
                return _media;
            }
        }

    }

    public class Medium6
    {
        private JObject __jobject;
        public Medium6(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Thumb3
    {
        private JObject __jobject;
        public Thumb3(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Small3
    {
        private JObject __jobject;
        public Small3(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Large3
    {
        private JObject __jobject;
        public Large3(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Sizes3
    {
        private JObject __jobject;
        public Sizes3(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Medium6 _medium;
        public Medium6 Medium
        {
            get
            {
                if (_medium == null)
                    _medium = JsonClassHelper.ReadStronglyTypedObject<Medium6>(JsonClassHelper.GetJToken<JObject>(__jobject, "medium"));
                return _medium;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Thumb3 _thumb;
        public Thumb3 Thumb
        {
            get
            {
                if (_thumb == null)
                    _thumb = JsonClassHelper.ReadStronglyTypedObject<Thumb3>(JsonClassHelper.GetJToken<JObject>(__jobject, "thumb"));
                return _thumb;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Small3 _small;
        public Small3 Small
        {
            get
            {
                if (_small == null)
                    _small = JsonClassHelper.ReadStronglyTypedObject<Small3>(JsonClassHelper.GetJToken<JObject>(__jobject, "small"));
                return _small;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Large3 _large;
        public Large3 Large
        {
            get
            {
                if (_large == null)
                    _large = JsonClassHelper.ReadStronglyTypedObject<Large3>(JsonClassHelper.GetJToken<JObject>(__jobject, "large"));
                return _large;
            }
        }

    }

    public class Medium5
    {
        private JObject __jobject;
        public Medium5(JObject obj)
        {
            this.__jobject = obj;
        }

        public long Id
        {
            get
            {
                return JsonClassHelper.ReadLong(JsonClassHelper.GetJToken<JValue>(__jobject, "id"));
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

        public string MediaUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "media_url"));
            }
        }

        public string MediaUrlHttps
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "media_url_https"));
            }
        }

        public string Url
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "url"));
            }
        }

        public string DisplayUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "display_url"));
            }
        }

        public string ExpandedUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "expanded_url"));
            }
        }

        public string Type
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "type"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Sizes3 _sizes;
        public Sizes3 Sizes
        {
            get
            {
                if (_sizes == null)
                    _sizes = JsonClassHelper.ReadStronglyTypedObject<Sizes3>(JsonClassHelper.GetJToken<JObject>(__jobject, "sizes"));
                return _sizes;
            }
        }

    }

    public class ExtendedEntities
    {
        private JObject __jobject;
        public ExtendedEntities(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Medium5> _media;
        public IList<Medium5> Media
        {
            get
            {
                if (_media == null)
                    _media = (IList<Medium5>)JsonClassHelper.ReadArray<Medium5>(JsonClassHelper.GetJToken<JArray>(__jobject, "media"), JsonClassHelper.ReadStronglyTypedObject<Medium5>, typeof(IList<Medium5>));
                return _media;
            }
        }

    }

    public class RetweetedStatus
    {
        private JObject __jobject;
        public RetweetedStatus(JObject obj)
        {
            this.__jobject = obj;
        }

        public string CreatedAt
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "created_at"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private object _id;
        public object Id
        {
            get
            {
                if (_id == null)
                    _id = JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "id"));
                return _id;
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        public string Text
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "text"));
            }
        }

        public string Source
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "source"));
            }
        }

        public bool Truncated
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "truncated"));
            }
        }

        public object InReplyToStatusId
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "in_reply_to_status_id"));
            }
        }

        public object InReplyToStatusIdStr
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "in_reply_to_status_id_str"));
            }
        }

        public object InReplyToUserId
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "in_reply_to_user_id"));
            }
        }

        public object InReplyToUserIdStr
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "in_reply_to_user_id_str"));
            }
        }

        public object InReplyToScreenName
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "in_reply_to_screen_name"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private User2 _user;
        public User2 User
        {
            get
            {
                if (_user == null)
                    _user = JsonClassHelper.ReadStronglyTypedObject<User2>(JsonClassHelper.GetJToken<JObject>(__jobject, "user"));
                return _user;
            }
        }

        public object Geo
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "geo"));
            }
        }

        public object Coordinates
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "coordinates"));
            }
        }

        public object Place
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "place"));
            }
        }

        public object Contributors
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "contributors"));
            }
        }

        public int RetweetCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "retweet_count"));
            }
        }

        public int FavoriteCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "favorite_count"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Entities4 _entities;
        public Entities4 Entities
        {
            get
            {
                if (_entities == null)
                    _entities = JsonClassHelper.ReadStronglyTypedObject<Entities4>(JsonClassHelper.GetJToken<JObject>(__jobject, "entities"));
                return _entities;
            }
        }

        public bool Favorited
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "favorited"));
            }
        }

        public bool Retweeted
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "retweeted"));
            }
        }

        public string Lang
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "lang"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private ExtendedEntities _extendedEntities;
        public ExtendedEntities ExtendedEntities
        {
            get
            {
                if (_extendedEntities == null)
                    _extendedEntities = JsonClassHelper.ReadStronglyTypedObject<ExtendedEntities>(JsonClassHelper.GetJToken<JObject>(__jobject, "extended_entities"));
                return _extendedEntities;
            }
        }

        public bool? PossiblySensitive
        {
            get
            {
                return JsonClassHelper.ReadNullableBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "possibly_sensitive"));
            }
        }

    }

    public class Thumb4
    {
        private JObject __jobject;
        public Thumb4(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Small4
    {
        private JObject __jobject;
        public Small4(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Large4
    {
        private JObject __jobject;
        public Large4(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Medium8
    {
        private JObject __jobject;
        public Medium8(JObject obj)
        {
            this.__jobject = obj;
        }

        public int W
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "w"));
            }
        }

        public int H
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "h"));
            }
        }

        public string Resize
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "resize"));
            }
        }

    }

    public class Sizes4
    {
        private JObject __jobject;
        public Sizes4(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Thumb4 _thumb;
        public Thumb4 Thumb
        {
            get
            {
                if (_thumb == null)
                    _thumb = JsonClassHelper.ReadStronglyTypedObject<Thumb4>(JsonClassHelper.GetJToken<JObject>(__jobject, "thumb"));
                return _thumb;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Small4 _small;
        public Small4 Small
        {
            get
            {
                if (_small == null)
                    _small = JsonClassHelper.ReadStronglyTypedObject<Small4>(JsonClassHelper.GetJToken<JObject>(__jobject, "small"));
                return _small;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Large4 _large;
        public Large4 Large
        {
            get
            {
                if (_large == null)
                    _large = JsonClassHelper.ReadStronglyTypedObject<Large4>(JsonClassHelper.GetJToken<JObject>(__jobject, "large"));
                return _large;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Medium8 _medium;
        public Medium8 Medium
        {
            get
            {
                if (_medium == null)
                    _medium = JsonClassHelper.ReadStronglyTypedObject<Medium8>(JsonClassHelper.GetJToken<JObject>(__jobject, "medium"));
                return _medium;
            }
        }

    }

    public class Medium7
    {
        private JObject __jobject;
        public Medium7(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private object _id;
        public object Id
        {
            get
            {
                if (_id == null)
                    _id = JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "id"));
                return _id;
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<int> _indices;
        public IList<int> Indices
        {
            get
            {
                if (_indices == null)
                    _indices = (IList<int>)JsonClassHelper.ReadArray<int>(JsonClassHelper.GetJToken<JArray>(__jobject, "indices"), JsonClassHelper.ReadInteger, typeof(IList<int>));
                return _indices;
            }
        }

        public string MediaUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "media_url"));
            }
        }

        public string MediaUrlHttps
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "media_url_https"));
            }
        }

        public string Url
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "url"));
            }
        }

        public string DisplayUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "display_url"));
            }
        }

        public string ExpandedUrl
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "expanded_url"));
            }
        }

        public string Type
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "type"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Sizes4 _sizes;
        public Sizes4 Sizes
        {
            get
            {
                if (_sizes == null)
                    _sizes = JsonClassHelper.ReadStronglyTypedObject<Sizes4>(JsonClassHelper.GetJToken<JObject>(__jobject, "sizes"));
                return _sizes;
            }
        }

        public long? SourceStatusId
        {
            get
            {
                return JsonClassHelper.ReadNullableLong(JsonClassHelper.GetJToken<JValue>(__jobject, "source_status_id"));
            }
        }

        public string SourceStatusIdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "source_status_id_str"));
            }
        }

    }

    public class ExtendedEntities2
    {
        private JObject __jobject;
        public ExtendedEntities2(JObject obj)
        {
            this.__jobject = obj;
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private IList<Medium7> _media;
        public IList<Medium7> Media
        {
            get
            {
                if (_media == null)
                    _media = (IList<Medium7>)JsonClassHelper.ReadArray<Medium7>(JsonClassHelper.GetJToken<JArray>(__jobject, "media"), JsonClassHelper.ReadStronglyTypedObject<Medium7>, typeof(IList<Medium7>));
                return _media;
            }
        }

    }

    public class TwitterModel2
    {

        public TwitterModel2(string json)
            : this(JObject.Parse(json))
        {
        }

        private JObject __jobject;
        public TwitterModel2(JObject obj)
        {
            this.__jobject = obj;
        }

        public string CreatedAt
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "created_at"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private object _id;
        public object Id
        {
            get
            {
                if (_id == null)
                    _id = JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "id"));
                return _id;
            }
        }

        public string IdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "id_str"));
            }
        }

        public string Text
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "text"));
            }
        }

        public string Source
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "source"));
            }
        }

        public bool Truncated
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "truncated"));
            }
        }

        public long? InReplyToStatusId
        {
            get
            {
                return JsonClassHelper.ReadNullableLong(JsonClassHelper.GetJToken<JValue>(__jobject, "in_reply_to_status_id"));
            }
        }

        public string InReplyToStatusIdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "in_reply_to_status_id_str"));
            }
        }

        public int? InReplyToUserId
        {
            get
            {
                return JsonClassHelper.ReadNullableInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "in_reply_to_user_id"));
            }
        }

        public string InReplyToUserIdStr
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "in_reply_to_user_id_str"));
            }
        }

        public string InReplyToScreenName
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "in_reply_to_screen_name"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private User _user;
        public User User
        {
            get
            {
                if (_user == null)
                    _user = JsonClassHelper.ReadStronglyTypedObject<User>(JsonClassHelper.GetJToken<JObject>(__jobject, "user"));
                return _user;
            }
        }

        public object Geo
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "geo"));
            }
        }

        public object Coordinates
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "coordinates"));
            }
        }

        public object Place
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "place"));
            }
        }

        public object Contributors
        {
            get
            {
                return JsonClassHelper.ReadObject(JsonClassHelper.GetJToken<JToken>(__jobject, "contributors"));
            }
        }

        public int RetweetCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "retweet_count"));
            }
        }

        public int FavoriteCount
        {
            get
            {
                return JsonClassHelper.ReadInteger(JsonClassHelper.GetJToken<JValue>(__jobject, "favorite_count"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private Entities2 _entities;
        public Entities2 Entities
        {
            get
            {
                if (_entities == null)
                    _entities = JsonClassHelper.ReadStronglyTypedObject<Entities2>(JsonClassHelper.GetJToken<JObject>(__jobject, "entities"));
                return _entities;
            }
        }

        public bool Favorited
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "favorited"));
            }
        }

        public bool Retweeted
        {
            get
            {
                return JsonClassHelper.ReadBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "retweeted"));
            }
        }

        public string Lang
        {
            get
            {
                return JsonClassHelper.ReadString(JsonClassHelper.GetJToken<JValue>(__jobject, "lang"));
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private RetweetedStatus _retweetedStatus;
        public RetweetedStatus RetweetedStatus
        {
            get
            {
                if (_retweetedStatus == null)
                    _retweetedStatus = JsonClassHelper.ReadStronglyTypedObject<RetweetedStatus>(JsonClassHelper.GetJToken<JObject>(__jobject, "retweeted_status"));
                return _retweetedStatus;
            }
        }

        [System.Diagnostics.DebuggerBrowsable(System.Diagnostics.DebuggerBrowsableState.Never)]
        private ExtendedEntities2 _extendedEntities;
        public ExtendedEntities2 ExtendedEntities
        {
            get
            {
                if (_extendedEntities == null)
                    _extendedEntities = JsonClassHelper.ReadStronglyTypedObject<ExtendedEntities2>(JsonClassHelper.GetJToken<JObject>(__jobject, "extended_entities"));
                return _extendedEntities;
            }
        }

        public bool? PossiblySensitive
        {
            get
            {
                return JsonClassHelper.ReadNullableBoolean(JsonClassHelper.GetJToken<JValue>(__jobject, "possibly_sensitive"));
            }
        }

    }

}
