using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NascarApi.Models.Leaderboard
{
    public class LeaderboardFeed
    {
        public int CurrentLapNumber { get; set; }
        public int ElapsedTime { get; set; }
        public int FlagState { get; set; }
        public int HistoricalRaceID { get; set; }
        public int LapsInRace { get; set; }
        public int LapsToGo { get; set; }
        public int RaceID { get; set; }
        public int RunID { get; set; }
        public string RunName { get; set; }
        public int RunType { get; set; }
        public int SeriesID { get; set; }
        public int TrackID { get; set; }
        public string TrackName { get; set; }
        public double TrackLength { get; set; }
        public List<PassingModel> Passings { get; set; }
        public double BestLapTime { get; set; }
        public WeatherInfoModel weatherInfo { get; set; }
        public int NumberOfCautionSegments { get; set; }
        public int NumberOfCautions { get; set; }
        public int NumberOfLeadChanges { get; set; }
        public int NumberOfLeaders { get; set; }
    }

    /*
    {
    "CurrentLapNumber": 28,
    "ElapsedTime": 1078,
    "FlagState": 1,
    "HistoricalRaceID": 4319,
    "LapsInRace": 267,
    "LapsToGo": 239,
    "RaceID": 4319,
    "RunID": 19,
    "RunName": "Ford EcoBoost 400",
    "RunType": 3,
    "SeriesID": 1,
    "TrackID": 40,
    "TrackName": "Homestead Miami Speedway",
    "TrackLength": 1.5,
    "Passings":     [
                {
            "AverageRestartSpeed": 171.99,
            "AverageRunningPosition": 1.5,
            "AverageSpeed": 140.664,
            "BestLap": 2,
            "BestSpeed": 176.315,
            "BestTime": 30.627,
            "CarMake": "Chv",
            "CarNo": "24",
            "ElapsedTime": 1078,
            "FastestLaps": 13,
            "LapCount": 28,
            "LapsLed":             [
                                {
                    "CarNo": "24",
                    "FromLap": 1,
                    "ToLap": 12,
                    "TotalLaps": 12
                },
                                {
                    "CarNo": "24",
                    "FromLap": 26,
                    "ToLap": 28,
                    "TotalLaps": 3
                }
            ],
            "LastLapSpeed": 166.052,
            "LastLapTime": 32.52,
            "Passes": 3,
            "PassingDifferential": 2,
            "RaceRank": 1,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Drive To End Hunger",
            "StartPosition": 1,
            "TimesPassed": 1,
            "SFDelta": 0,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Jeff Gordon",
                "HistoricalDriverID": 1237,
                "IsInChase": false
            },
            "BonusPoints": 5,
            "DeltaLeader": -2682,
            "FirstName": "Jeff",
            "HistoricalID": 1237,
            "IsInChase": false,
            "LastName": "Gordon",
            "MembershipID": 3727,
            "Points": 2360,
            "PointsPosition": 5,
            "RunningPositionPoints": 43,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 172.084,
            "AverageRunningPosition": 1.857,
            "AverageSpeed": 140.509,
            "BestLap": 16,
            "BestSpeed": 174.678,
            "BestTime": 30.914,
            "CarMake": "Chv",
            "CarNo": "4",
            "ElapsedTime": 1076,
            "FastestLaps": 10,
            "LapCount": 28,
            "LapsLed": [            {
                "CarNo": "4",
                "FromLap": 15,
                "ToLap": 25,
                "TotalLaps": 11
            }],
            "LastLapSpeed": 164.004,
            "LastLapTime": 32.926,
            "Passes": 9,
            "PassingDifferential": 5,
            "RaceRank": 2,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Budweiser",
            "StartPosition": 5,
            "TimesPassed": 4,
            "SFDelta": 1.185,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Kevin Harvick",
                "HistoricalDriverID": 1416,
                "IsInChase": true
            },
            "BonusPoints": 0,
            "DeltaLeader": 0,
            "FirstName": "Kevin",
            "HistoricalID": 1416,
            "IsInChase": true,
            "LastName": "Harvick",
            "MembershipID": 6987,
            "Points": 5042,
            "PointsPosition": 1,
            "RunningPositionPoints": 42,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 170.35,
            "AverageRunningPosition": 4.286,
            "AverageSpeed": 139.469,
            "BestLap": 2,
            "BestSpeed": 173.734,
            "BestTime": 31.082,
            "CarMake": "Tyt",
            "CarNo": "11",
            "ElapsedTime": 1078,
            "FastestLaps": 1,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 165.588,
            "LastLapTime": 32.611,
            "Passes": 7,
            "PassingDifferential": 4,
            "RaceRank": 3,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "FedEx Express",
            "StartPosition": 8,
            "TimesPassed": 3,
            "SFDelta": 3.218,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Denny Hamlin",
                "HistoricalDriverID": 1361,
                "IsInChase": true
            },
            "BonusPoints": 0,
            "DeltaLeader": -1,
            "FirstName": "Denny",
            "HistoricalID": 1361,
            "IsInChase": true,
            "LastName": "Hamlin",
            "MembershipID": 21682,
            "Points": 5041,
            "PointsPosition": 2,
            "RunningPositionPoints": 41,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 169.438,
            "AverageRunningPosition": 6.852,
            "AverageSpeed": 139.421,
            "BestLap": 2,
            "BestSpeed": 173.16,
            "BestTime": 31.185,
            "CarMake": "Frd",
            "CarNo": "22",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 166.924,
            "LastLapTime": 32.35,
            "Passes": 8,
            "PassingDifferential": 5,
            "RaceRank": 4,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Shell Pennzoil",
            "StartPosition": 9,
            "TimesPassed": 3,
            "SFDelta": 3.375,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Joey Logano",
                "HistoricalDriverID": 3859,
                "IsInChase": true
            },
            "BonusPoints": 0,
            "DeltaLeader": -2,
            "FirstName": "Joey",
            "HistoricalID": 3859,
            "IsInChase": true,
            "LastName": "Logano",
            "MembershipID": 151509,
            "Points": 5040,
            "PointsPosition": 3,
            "RunningPositionPoints": 40,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 168.753,
            "AverageRunningPosition": 8.852,
            "AverageSpeed": 139.304,
            "BestLap": 16,
            "BestSpeed": 172.403,
            "BestTime": 31.322,
            "CarMake": "Chv",
            "CarNo": "88",
            "ElapsedTime": 1076,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 166.302,
            "LastLapTime": 32.471,
            "Passes": 6,
            "PassingDifferential": 6,
            "RaceRank": 5,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "National Guard",
            "StartPosition": 11,
            "TimesPassed": 0,
            "SFDelta": 4.248,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Dale Earnhardt Jr.",
                "HistoricalDriverID": 915,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2732,
            "FirstName": "Dale",
            "HistoricalID": 915,
            "IsInChase": false,
            "LastName": "Earnhardt Jr.",
            "MembershipID": 3638,
            "Points": 2310,
            "PointsPosition": 8,
            "RunningPositionPoints": 39,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 170.444,
            "AverageRunningPosition": 3.852,
            "AverageSpeed": 139.147,
            "BestLap": 2,
            "BestSpeed": 174.774,
            "BestTime": 30.897,
            "CarMake": "Tyt",
            "CarNo": "20",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 164.624,
            "LastLapTime": 32.802,
            "Passes": 6,
            "PassingDifferential": -1,
            "RaceRank": 6,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Dollar General",
            "StartPosition": 3,
            "TimesPassed": 7,
            "SFDelta": 5.427,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Matt Kenseth",
                "HistoricalDriverID": 1810,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2708,
            "FirstName": "Matt",
            "HistoricalID": 1810,
            "IsInChase": false,
            "LastName": "Kenseth",
            "MembershipID": 8188,
            "Points": 2334,
            "PointsPosition": 7,
            "RunningPositionPoints": 38,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 168.573,
            "AverageRunningPosition": 7.407,
            "AverageSpeed": 139.008,
            "BestLap": 2,
            "BestSpeed": 173.723,
            "BestTime": 31.084,
            "CarMake": "Frd",
            "CarNo": "2",
            "ElapsedTime": 1073,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 165.35,
            "LastLapTime": 32.658,
            "Passes": 11,
            "PassingDifferential": 1,
            "RaceRank": 7,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Miller Lite",
            "StartPosition": 4,
            "TimesPassed": 10,
            "SFDelta": 6.478,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Brad Keselowski",
                "HistoricalDriverID": 1816,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2685,
            "FirstName": "Brad",
            "HistoricalID": 1816,
            "IsInChase": false,
            "LastName": "Keselowski",
            "MembershipID": 70634,
            "Points": 2357,
            "PointsPosition": 6,
            "RunningPositionPoints": 37,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 167.776,
            "AverageRunningPosition": 10.852,
            "AverageSpeed": 138.822,
            "BestLap": 2,
            "BestSpeed": 171.282,
            "BestTime": 31.527,
            "CarMake": "Chv",
            "CarNo": "48",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 164.931,
            "LastLapTime": 32.741,
            "Passes": 11,
            "PassingDifferential": 4,
            "RaceRank": 8,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Lowe's",
            "StartPosition": 12,
            "TimesPassed": 7,
            "SFDelta": 7.885,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Jimmie Johnson",
                "HistoricalDriverID": 1717,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2767,
            "FirstName": "Jimmie",
            "HistoricalID": 1717,
            "IsInChase": false,
            "LastName": "Johnson",
            "MembershipID": 35846,
            "Points": 2275,
            "PointsPosition": 12,
            "RunningPositionPoints": 36,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 168.71,
            "AverageRunningPosition": 8.704,
            "AverageSpeed": 138.777,
            "BestLap": 2,
            "BestSpeed": 172.905,
            "BestTime": 31.231,
            "CarMake": "Tyt",
            "CarNo": "15",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 164.961,
            "LastLapTime": 32.735,
            "Passes": 5,
            "PassingDifferential": -5,
            "RaceRank": 9,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "5-hour Energy",
            "StartPosition": 6,
            "TimesPassed": 10,
            "SFDelta": 8.225,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Clint Bowyer",
                "HistoricalDriverID": 339,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4064,
            "FirstName": "Clint",
            "HistoricalID": 339,
            "IsInChase": false,
            "LastName": "Bowyer",
            "MembershipID": 48591,
            "Points": 978,
            "PointsPosition": 19,
            "RunningPositionPoints": 35,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 169.088,
            "AverageRunningPosition": 5.37,
            "AverageSpeed": 138.706,
            "BestLap": 2,
            "BestSpeed": 173.221,
            "BestTime": 31.174,
            "CarMake": "Chv",
            "CarNo": "41",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [            {
                "CarNo": "41",
                "FromLap": 14,
                "ToLap": 14,
                "TotalLaps": 1
            }],
            "LastLapSpeed": 164.139,
            "LastLapTime": 32.899,
            "Passes": 7,
            "PassingDifferential": -12,
            "RaceRank": 10,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Haas Automation",
            "StartPosition": 2,
            "TimesPassed": 19,
            "SFDelta": 8.764,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Kurt Busch",
                "HistoricalDriverID": 453,
                "IsInChase": false
            },
            "BonusPoints": 1,
            "DeltaLeader": -2778,
            "FirstName": "Kurt",
            "HistoricalID": 453,
            "IsInChase": false,
            "LastName": "Busch",
            "MembershipID": 1754,
            "Points": 2264,
            "PointsPosition": 13,
            "RunningPositionPoints": 34,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 167.638,
            "AverageRunningPosition": 14.667,
            "AverageSpeed": 138.678,
            "BestLap": 2,
            "BestSpeed": 170.8,
            "BestTime": 31.616,
            "CarMake": "Chv",
            "CarNo": "5",
            "ElapsedTime": 1076,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 164.409,
            "LastLapTime": 32.845,
            "Passes": 19,
            "PassingDifferential": 12,
            "RaceRank": 11,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Great Clips",
            "StartPosition": 23,
            "TimesPassed": 7,
            "SFDelta": 8.973,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Kasey Kahne",
                "HistoricalDriverID": 1772,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2807,
            "FirstName": "Kasey",
            "HistoricalID": 1772,
            "IsInChase": false,
            "LastName": "Kahne",
            "MembershipID": 105217,
            "Points": 2235,
            "PointsPosition": 15,
            "RunningPositionPoints": 33,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 168.235,
            "AverageRunningPosition": 11.185,
            "AverageSpeed": 138.589,
            "BestLap": 2,
            "BestSpeed": 172.601,
            "BestTime": 31.286,
            "CarMake": "Chv",
            "CarNo": "78",
            "ElapsedTime": 1076,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 164.114,
            "LastLapTime": 32.904,
            "Passes": 7,
            "PassingDifferential": 1,
            "RaceRank": 12,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Furniture Row",
            "StartPosition": 10,
            "TimesPassed": 6,
            "SFDelta": 9.653,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Martin Truex Jr.",
                "HistoricalDriverID": 3368,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4180,
            "FirstName": "Martin",
            "HistoricalID": 3368,
            "IsInChase": false,
            "LastName": "Truex Jr.",
            "MembershipID": 45125,
            "Points": 862,
            "PointsPosition": 24,
            "RunningPositionPoints": 32,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 166.819,
            "AverageRunningPosition": 16.222,
            "AverageSpeed": 138.506,
            "BestLap": 16,
            "BestSpeed": 169.731,
            "BestTime": 31.815,
            "CarMake": "Chv",
            "CarNo": "31",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 163.944,
            "LastLapTime": 32.938,
            "Passes": 15,
            "PassingDifferential": 6,
            "RaceRank": 13,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Caterpillar",
            "StartPosition": 21,
            "TimesPassed": 9,
            "SFDelta": 10.284,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Ryan Newman",
                "HistoricalDriverID": 2394,
                "IsInChase": true
            },
            "BonusPoints": 0,
            "DeltaLeader": -11,
            "FirstName": "Ryan",
            "HistoricalID": 2394,
            "IsInChase": true,
            "LastName": "Newman",
            "MembershipID": 8859,
            "Points": 5031,
            "PointsPosition": 4,
            "RunningPositionPoints": 31,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 167.15,
            "AverageRunningPosition": 11.926,
            "AverageSpeed": 138.499,
            "BestLap": 2,
            "BestSpeed": 171.559,
            "BestTime": 31.476,
            "CarMake": "Tyt",
            "CarNo": "18",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 162.803,
            "LastLapTime": 33.169,
            "Passes": 12,
            "PassingDifferential": -8,
            "RaceRank": 14,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "M&M's",
            "StartPosition": 7,
            "TimesPassed": 20,
            "SFDelta": 10.331,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Kyle Busch",
                "HistoricalDriverID": 454,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2732,
            "FirstName": "Kyle",
            "HistoricalID": 454,
            "IsInChase": false,
            "LastName": "Busch",
            "MembershipID": 85071,
            "Points": 2310,
            "PointsPosition": 9,
            "RunningPositionPoints": 30,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 167.362,
            "AverageRunningPosition": 17.519,
            "AverageSpeed": 138.428,
            "BestLap": 16,
            "BestSpeed": 169.972,
            "BestTime": 31.77,
            "CarMake": "Chv",
            "CarNo": "42",
            "ElapsedTime": 1078,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 163.706,
            "LastLapTime": 32.986,
            "Passes": 29,
            "PassingDifferential": 10,
            "RaceRank": 15,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Target",
            "StartPosition": 27,
            "TimesPassed": 19,
            "SFDelta": 10.87,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Kyle Larson #",
                "HistoricalDriverID": 4030,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -3964,
            "FirstName": "Kyle",
            "HistoricalID": 4030,
            "IsInChase": false,
            "LastName": "Larson",
            "MembershipID": 187538,
            "Points": 1078,
            "PointsPosition": 17,
            "RunningPositionPoints": 29,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 166.93,
            "AverageRunningPosition": 16.444,
            "AverageSpeed": 138.242,
            "BestLap": 2,
            "BestSpeed": 171.816,
            "BestTime": 31.429,
            "CarMake": "Frd",
            "CarNo": "99",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 162.881,
            "LastLapTime": 33.153,
            "Passes": 13,
            "PassingDifferential": -1,
            "RaceRank": 16,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Fastenal",
            "StartPosition": 15,
            "TimesPassed": 14,
            "SFDelta": 12.294,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Carl Edwards",
                "HistoricalDriverID": 923,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2736,
            "FirstName": "Carl",
            "HistoricalID": 923,
            "IsInChase": false,
            "LastName": "Edwards",
            "MembershipID": 31197,
            "Points": 2306,
            "PointsPosition": 10,
            "RunningPositionPoints": 28,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 166.888,
            "AverageRunningPosition": 16.074,
            "AverageSpeed": 138.156,
            "BestLap": 2,
            "BestSpeed": 172.607,
            "BestTime": 31.285,
            "CarMake": "Chv",
            "CarNo": "1",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 162.284,
            "LastLapTime": 33.275,
            "Passes": 9,
            "PassingDifferential": 1,
            "RaceRank": 17,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Cessna",
            "StartPosition": 19,
            "TimesPassed": 8,
            "SFDelta": 12.946,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Jamie McMurray",
                "HistoricalDriverID": 2208,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4040,
            "FirstName": "Jamie",
            "HistoricalID": 2208,
            "IsInChase": false,
            "LastName": "McMurray",
            "MembershipID": 39567,
            "Points": 1002,
            "PointsPosition": 18,
            "RunningPositionPoints": 27,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 165.546,
            "AverageRunningPosition": 18.556,
            "AverageSpeed": 138.005,
            "BestLap": 2,
            "BestSpeed": 171.494,
            "BestTime": 31.488,
            "CarMake": "Tyt",
            "CarNo": "55",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 163.226,
            "LastLapTime": 33.083,
            "Passes": 16,
            "PassingDifferential": 3,
            "RaceRank": 18,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Aaron's Dream Machine",
            "StartPosition": 13,
            "TimesPassed": 13,
            "SFDelta": 14.101,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Brian Vickers",
                "HistoricalDriverID": 3425,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4116,
            "FirstName": "Brian",
            "HistoricalID": 3425,
            "IsInChase": false,
            "LastName": "Vickers",
            "MembershipID": 49176,
            "Points": 926,
            "PointsPosition": 21,
            "RunningPositionPoints": 26,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 167.102,
            "AverageRunningPosition": 19.889,
            "AverageSpeed": 137.975,
            "BestLap": 2,
            "BestSpeed": 171.614,
            "BestTime": 31.466,
            "CarMake": "Chv",
            "CarNo": "47",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 161.987,
            "LastLapTime": 33.336,
            "Passes": 15,
            "PassingDifferential": 5,
            "RaceRank": 19,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Hungry Jack",
            "StartPosition": 25,
            "TimesPassed": 10,
            "SFDelta": 14.335,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "AJ Allmendinger",
                "HistoricalDriverID": 3774,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2761,
            "FirstName": "A J",
            "HistoricalID": 3774,
            "IsInChase": false,
            "LastName": "Allmendinger",
            "MembershipID": 149643,
            "Points": 2281,
            "PointsPosition": 11,
            "RunningPositionPoints": 25,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 165.102,
            "AverageRunningPosition": 18.778,
            "AverageSpeed": 137.886,
            "BestLap": 2,
            "BestSpeed": 169.55,
            "BestTime": 31.849,
            "CarMake": "Chv",
            "CarNo": "51",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 162.911,
            "LastLapTime": 33.147,
            "Passes": 8,
            "PassingDifferential": -5,
            "RaceRank": 20,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "BRANDT",
            "StartPosition": 14,
            "TimesPassed": 13,
            "SFDelta": 15.014,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Justin Allgaier #",
                "HistoricalDriverID": 34,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4411,
            "FirstName": "Justin",
            "HistoricalID": 34,
            "IsInChase": false,
            "LastName": "Allgaier",
            "MembershipID": 137055,
            "Points": 631,
            "PointsPosition": 29,
            "RunningPositionPoints": 24,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 165.732,
            "AverageRunningPosition": 23.667,
            "AverageSpeed": 137.649,
            "BestLap": 2,
            "BestSpeed": 168.245,
            "BestTime": 32.096,
            "CarMake": "Frd",
            "CarNo": "21",
            "ElapsedTime": 1076,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 161.807,
            "LastLapTime": 33.373,
            "Passes": 9,
            "PassingDifferential": -2,
            "RaceRank": 21,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Motorcraft/Quick Lane Tire & Auto Center",
            "StartPosition": 26,
            "TimesPassed": 11,
            "SFDelta": 16.833,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Trevor Bayne(i)",
                "HistoricalDriverID": 3883,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -5042,
            "FirstName": "Trevor",
            "HistoricalID": 3883,
            "IsInChase": false,
            "LastName": "Bayne",
            "MembershipID": 151855,
            "Points": 0,
            "PointsPosition": 59,
            "RunningPositionPoints": 0,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 164.718,
            "AverageRunningPosition": 23.963,
            "AverageSpeed": 137.629,
            "BestLap": 2,
            "BestSpeed": 168.724,
            "BestTime": 32.005,
            "CarMake": "Chv",
            "CarNo": "10",
            "ElapsedTime": 1076,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 162.07,
            "LastLapTime": 33.319,
            "Passes": 17,
            "PassingDifferential": 3,
            "RaceRank": 22,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Florida Lottery/GoDaddy",
            "StartPosition": 32,
            "TimesPassed": 14,
            "SFDelta": 16.991,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Danica Patrick",
                "HistoricalDriverID": 3929,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4311,
            "FirstName": "Danica",
            "HistoricalID": 3929,
            "IsInChase": false,
            "LastName": "Patrick",
            "MembershipID": 171547,
            "Points": 731,
            "PointsPosition": 28,
            "RunningPositionPoints": 22,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 164.244,
            "AverageRunningPosition": 26.889,
            "AverageSpeed": 137.573,
            "BestLap": 2,
            "BestSpeed": 166.374,
            "BestTime": 32.457,
            "CarMake": "Chv",
            "CarNo": "3",
            "ElapsedTime": 1076,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 162.602,
            "LastLapTime": 33.21,
            "Passes": 20,
            "PassingDifferential": -4,
            "RaceRank": 23,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Dow",
            "StartPosition": 24,
            "TimesPassed": 24,
            "SFDelta": 17.421,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Austin Dillon #",
                "HistoricalDriverID": 3873,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4082,
            "FirstName": "Austin",
            "HistoricalID": 3873,
            "IsInChase": false,
            "LastName": "Dillon",
            "MembershipID": 150743,
            "Points": 960,
            "PointsPosition": 20,
            "RunningPositionPoints": 21,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 164.786,
            "AverageRunningPosition": 25.37,
            "AverageSpeed": 137.51,
            "BestLap": 2,
            "BestSpeed": 168.655,
            "BestTime": 32.018,
            "CarMake": "Frd",
            "CarNo": "16",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 162.118,
            "LastLapTime": 33.309,
            "Passes": 17,
            "PassingDifferential": -2,
            "RaceRank": 24,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "3M",
            "StartPosition": 20,
            "TimesPassed": 19,
            "SFDelta": 17.904,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Greg Biffle",
                "HistoricalDriverID": 243,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2778,
            "FirstName": "Greg",
            "HistoricalID": 243,
            "IsInChase": false,
            "LastName": "Biffle",
            "MembershipID": 2606,
            "Points": 2264,
            "PointsPosition": 14,
            "RunningPositionPoints": 20,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 166.132,
            "AverageRunningPosition": 29.222,
            "AverageSpeed": 137.473,
            "BestLap": 2,
            "BestSpeed": 170.223,
            "BestTime": 31.723,
            "CarMake": "Chv",
            "CarNo": "27",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 161.662,
            "LastLapTime": 33.403,
            "Passes": 36,
            "PassingDifferential": 27,
            "RaceRank": 25,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Richmond/Menards",
            "StartPosition": 16,
            "TimesPassed": 9,
            "SFDelta": 18.19,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Paul Menard",
                "HistoricalDriverID": 2225,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4119,
            "FirstName": "Paul",
            "HistoricalID": 2225,
            "IsInChase": false,
            "LastName": "Menard",
            "MembershipID": 69496,
            "Points": 923,
            "PointsPosition": 22,
            "RunningPositionPoints": 19,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 166.298,
            "AverageRunningPosition": 20.259,
            "AverageSpeed": 137.405,
            "BestLap": 2,
            "BestSpeed": 169.099,
            "BestTime": 31.934,
            "CarMake": "Chv",
            "CarNo": "14",
            "ElapsedTime": 1078,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 159.82,
            "LastLapTime": 33.788,
            "Passes": 11,
            "PassingDifferential": -15,
            "RaceRank": 26,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Bass Pro Shops/Mobil 1",
            "StartPosition": 28,
            "TimesPassed": 26,
            "SFDelta": 18.711,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Tony Stewart",
                "HistoricalDriverID": 3193,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4226,
            "FirstName": "Tony",
            "HistoricalID": 3193,
            "IsInChase": false,
            "LastName": "Stewart",
            "MembershipID": 3636,
            "Points": 816,
            "PointsPosition": 25,
            "RunningPositionPoints": 18,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 164.318,
            "AverageRunningPosition": 25.259,
            "AverageSpeed": 137.317,
            "BestLap": 2,
            "BestSpeed": 168.524,
            "BestTime": 32.043,
            "CarMake": "Frd",
            "CarNo": "17",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 161.904,
            "LastLapTime": 33.353,
            "Passes": 15,
            "PassingDifferential": -8,
            "RaceRank": 27,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Fastenal",
            "StartPosition": 22,
            "TimesPassed": 23,
            "SFDelta": 19.396,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Ricky Stenhouse Jr.",
                "HistoricalDriverID": 3888,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4290,
            "FirstName": "Ricky",
            "HistoricalID": 3888,
            "IsInChase": false,
            "LastName": "Stenhouse Jr.",
            "MembershipID": 159009,
            "Points": 752,
            "PointsPosition": 27,
            "RunningPositionPoints": 17,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 166.173,
            "AverageRunningPosition": 25.37,
            "AverageSpeed": 137.303,
            "BestLap": 2,
            "BestSpeed": 168.945,
            "BestTime": 31.963,
            "CarMake": "Frd",
            "CarNo": "43",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 160.499,
            "LastLapTime": 33.645,
            "Passes": 29,
            "PassingDifferential": 9,
            "RaceRank": 28,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Smithfield Foods",
            "StartPosition": 18,
            "TimesPassed": 20,
            "SFDelta": 19.505,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Aric Almirola",
                "HistoricalDriverID": 40,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -2856,
            "FirstName": "Aric",
            "HistoricalID": 40,
            "IsInChase": false,
            "LastName": "Almirola",
            "MembershipID": 127822,
            "Points": 2186,
            "PointsPosition": 16,
            "RunningPositionPoints": 16,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 165.45,
            "AverageRunningPosition": 29.444,
            "AverageSpeed": 137.267,
            "BestLap": 2,
            "BestSpeed": 168.324,
            "BestTime": 32.081,
            "CarMake": "Frd",
            "CarNo": "9",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 160.223,
            "LastLapTime": 33.703,
            "Passes": 19,
            "PassingDifferential": 5,
            "RaceRank": 29,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Stanley",
            "StartPosition": 17,
            "TimesPassed": 14,
            "SFDelta": 19.781,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Marcos Ambrose",
                "HistoricalDriverID": 49,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4174,
            "FirstName": "Marcos",
            "HistoricalID": 49,
            "IsInChase": false,
            "LastName": "Ambrose",
            "MembershipID": 144082,
            "Points": 868,
            "PointsPosition": 23,
            "RunningPositionPoints": 15,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 163.422,
            "AverageRunningPosition": 32.778,
            "AverageSpeed": 137.201,
            "BestLap": 3,
            "BestSpeed": 167.546,
            "BestTime": 32.23,
            "CarMake": "Chv",
            "CarNo": "33",
            "ElapsedTime": 1076,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 162.299,
            "LastLapTime": 33.272,
            "Passes": 30,
            "PassingDifferential": 11,
            "RaceRank": 30,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Shore Lodge",
            "StartPosition": 30,
            "TimesPassed": 19,
            "SFDelta": 20.292,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Brian Scott(i)",
                "HistoricalDriverID": 3822,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -5042,
            "FirstName": "Brian",
            "HistoricalID": 3822,
            "IsInChase": false,
            "LastName": "Scott",
            "MembershipID": 158478,
            "Points": 0,
            "PointsPosition": 62,
            "RunningPositionPoints": 0,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 166.139,
            "AverageRunningPosition": 27.37,
            "AverageSpeed": 137.074,
            "BestLap": 2,
            "BestSpeed": 167.801,
            "BestTime": 32.181,
            "CarMake": "Chv",
            "CarNo": "13",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 160.385,
            "LastLapTime": 33.669,
            "Passes": 10,
            "PassingDifferential": -6,
            "RaceRank": 31,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "GEICO",
            "StartPosition": 29,
            "TimesPassed": 16,
            "SFDelta": 21.276,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Casey Mears",
                "HistoricalDriverID": 2215,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4271,
            "FirstName": "Casey",
            "HistoricalID": 2215,
            "IsInChase": false,
            "LastName": "Mears",
            "MembershipID": 104147,
            "Points": 771,
            "PointsPosition": 26,
            "RunningPositionPoints": 13,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 164.551,
            "AverageRunningPosition": 31.556,
            "AverageSpeed": 137.03,
            "BestLap": 2,
            "BestSpeed": 167.007,
            "BestTime": 32.334,
            "CarMake": "Frd",
            "CarNo": "95",
            "ElapsedTime": 1077,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 159.287,
            "LastLapTime": 33.901,
            "Passes": 11,
            "PassingDifferential": -3,
            "RaceRank": 32,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "KLOVE Radio/Thrivent Financial",
            "StartPosition": 38,
            "TimesPassed": 14,
            "SFDelta": 21.622,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Michael McDowell",
                "HistoricalDriverID": 3832,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4798,
            "FirstName": "Michael",
            "HistoricalID": 3832,
            "IsInChase": false,
            "LastName": "McDowell",
            "MembershipID": 158758,
            "Points": 244,
            "PointsPosition": 37,
            "RunningPositionPoints": 12,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 164.272,
            "AverageRunningPosition": 35.222,
            "AverageSpeed": 136.978,
            "BestLap": 3,
            "BestSpeed": 166.067,
            "BestTime": 32.517,
            "CarMake": "Tyt",
            "CarNo": "23",
            "ElapsedTime": 1078,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 160.261,
            "LastLapTime": 33.695,
            "Passes": 20,
            "PassingDifferential": 0,
            "RaceRank": 33,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Dip Your Car",
            "StartPosition": 41,
            "TimesPassed": 20,
            "SFDelta": 22.019,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Alex Bowman #",
                "HistoricalDriverID": 4045,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4630,
            "FirstName": "Alex",
            "HistoricalID": 4045,
            "IsInChase": false,
            "LastName": "Bowman",
            "MembershipID": 180815,
            "Points": 412,
            "PointsPosition": 35,
            "RunningPositionPoints": 11,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 165.556,
            "AverageRunningPosition": 31.074,
            "AverageSpeed": 136.931,
            "BestLap": 2,
            "BestSpeed": 169.072,
            "BestTime": 31.939,
            "CarMake": "Frd",
            "CarNo": "34",
            "ElapsedTime": 1078,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 159.877,
            "LastLapTime": 33.776,
            "Passes": 8,
            "PassingDifferential": -1,
            "RaceRank": 34,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "The Pete Store",
            "StartPosition": 31,
            "TimesPassed": 9,
            "SFDelta": 22.386,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "David Ragan",
                "HistoricalDriverID": 2674,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4515,
            "FirstName": "David",
            "HistoricalID": 2674,
            "IsInChase": false,
            "LastName": "Ragan",
            "MembershipID": 114952,
            "Points": 527,
            "PointsPosition": 31,
            "RunningPositionPoints": 10,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 164.338,
            "AverageRunningPosition": 36.926,
            "AverageSpeed": 136.894,
            "BestLap": 2,
            "BestSpeed": 168.004,
            "BestTime": 32.142,
            "CarMake": "Tyt",
            "CarNo": "26",
            "ElapsedTime": 1078,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 159.208,
            "LastLapTime": 33.918,
            "Passes": 17,
            "PassingDifferential": -5,
            "RaceRank": 35,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Speed Stick Gear",
            "StartPosition": 42,
            "TimesPassed": 22,
            "SFDelta": 22.675,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Cole Whitt #",
                "HistoricalDriverID": 3979,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4519,
            "FirstName": "Cole",
            "HistoricalID": 3979,
            "IsInChase": false,
            "LastName": "Whitt",
            "MembershipID": 158791,
            "Points": 523,
            "PointsPosition": 32,
            "RunningPositionPoints": 9,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 163.632,
            "AverageRunningPosition": 32.815,
            "AverageSpeed": 136.863,
            "BestLap": 2,
            "BestSpeed": 167.317,
            "BestTime": 32.274,
            "CarMake": "Chv",
            "CarNo": "36",
            "ElapsedTime": 1074,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 160.423,
            "LastLapTime": 33.661,
            "Passes": 20,
            "PassingDifferential": -1,
            "RaceRank": 36,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Feed The Children/Dei Fratelli",
            "StartPosition": 36,
            "TimesPassed": 21,
            "SFDelta": 22.92,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Reed Sorenson",
                "HistoricalDriverID": 3120,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4538,
            "FirstName": "Reed",
            "HistoricalID": 3120,
            "IsInChase": false,
            "LastName": "Sorenson",
            "MembershipID": 128516,
            "Points": 504,
            "PointsPosition": 34,
            "RunningPositionPoints": 8,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 163.454,
            "AverageRunningPosition": 35.852,
            "AverageSpeed": 136.758,
            "BestLap": 2,
            "BestSpeed": 166.976,
            "BestTime": 32.34,
            "CarMake": "Chv",
            "CarNo": "40",
            "ElapsedTime": 1074,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 160.371,
            "LastLapTime": 33.672,
            "Passes": 13,
            "PassingDifferential": -10,
            "RaceRank": 37,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Harvey Gulf",
            "StartPosition": 33,
            "TimesPassed": 23,
            "SFDelta": 23.736,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Landon Cassill(i)",
                "HistoricalDriverID": 3808,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -5042,
            "FirstName": "Landon",
            "HistoricalID": 3808,
            "IsInChase": false,
            "LastName": "Cassill",
            "MembershipID": 155459,
            "Points": 0,
            "PointsPosition": 57,
            "RunningPositionPoints": 0,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 164.135,
            "AverageRunningPosition": 35.148,
            "AverageSpeed": 136.689,
            "BestLap": 2,
            "BestSpeed": 167.064,
            "BestTime": 32.323,
            "CarMake": "Frd",
            "CarNo": "38",
            "ElapsedTime": 1075,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 160.433,
            "LastLapTime": 33.659,
            "Passes": 12,
            "PassingDifferential": -3,
            "RaceRank": 38,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "MDS Transport",
            "StartPosition": 35,
            "TimesPassed": 15,
            "SFDelta": 24.27,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "David Gilliland",
                "HistoricalDriverID": 1202,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4495,
            "FirstName": "David",
            "HistoricalID": 1202,
            "IsInChase": false,
            "LastName": "Gilliland",
            "MembershipID": 4875,
            "Points": 547,
            "PointsPosition": 30,
            "RunningPositionPoints": 6,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 162.602,
            "AverageRunningPosition": 37.889,
            "AverageSpeed": 136.579,
            "BestLap": 4,
            "BestSpeed": 166.195,
            "BestTime": 32.492,
            "CarMake": "Chv",
            "CarNo": "98",
            "ElapsedTime": 1076,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 158.917,
            "LastLapTime": 33.98,
            "Passes": 6,
            "PassingDifferential": -3,
            "RaceRank": 39,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "PPR98.com",
            "StartPosition": 37,
            "TimesPassed": 9,
            "SFDelta": 25.134,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Josh Wise",
                "HistoricalDriverID": 3797,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4644,
            "FirstName": "Josh",
            "HistoricalID": 3797,
            "IsInChase": false,
            "LastName": "Wise",
            "MembershipID": 150171,
            "Points": 398,
            "PointsPosition": 36,
            "RunningPositionPoints": 5,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 163.513,
            "AverageRunningPosition": 37.815,
            "AverageSpeed": 136.357,
            "BestLap": 2,
            "BestSpeed": 166.302,
            "BestTime": 32.471,
            "CarMake": "Tyt",
            "CarNo": "83",
            "ElapsedTime": 1078,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 158.707,
            "LastLapTime": 34.025,
            "Passes": 13,
            "PassingDifferential": -18,
            "RaceRank": 40,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Dip Your Car",
            "StartPosition": 34,
            "TimesPassed": 31,
            "SFDelta": 26.87,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "JJ Yeley(i)",
                "HistoricalDriverID": 3669,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -5042,
            "FirstName": "J J",
            "HistoricalID": 3669,
            "IsInChase": false,
            "LastName": "Yeley",
            "MembershipID": 126843,
            "Points": 0,
            "PointsPosition": 65,
            "RunningPositionPoints": 0,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 161.878,
            "AverageRunningPosition": 40.852,
            "AverageSpeed": 136.287,
            "BestLap": 3,
            "BestSpeed": 164.996,
            "BestTime": 32.728,
            "CarMake": "Tyt",
            "CarNo": "66",
            "ElapsedTime": 1078,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [],
            "LastLapSpeed": 158.168,
            "LastLapTime": 34.141,
            "Passes": 1,
            "PassingDifferential": -6,
            "RaceRank": 41,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "X8 Energy Gum",
            "StartPosition": 43,
            "TimesPassed": 7,
            "SFDelta": 27.423,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Brett Moffitt",
                "HistoricalDriverID": 4038,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4987,
            "FirstName": "Brett",
            "HistoricalID": 4038,
            "IsInChase": false,
            "LastName": "Moffitt",
            "MembershipID": 166674,
            "Points": 55,
            "PointsPosition": 45,
            "RunningPositionPoints": 3,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 160.604,
            "AverageRunningPosition": 39.321,
            "AverageSpeed": 135.455,
            "BestLap": 2,
            "BestSpeed": 165.097,
            "BestTime": 32.708,
            "CarMake": "Frd",
            "CarNo": "32",
            "ElapsedTime": 1076,
            "FastestLaps": 0,
            "LapCount": 27,
            "LapsLed": [            {
                "CarNo": "32",
                "FromLap": 13,
                "ToLap": 13,
                "TotalLaps": 1
            }],
            "LastLapSpeed": 155.611,
            "LastLapTime": 34.702,
            "Passes": 2,
            "PassingDifferential": -8,
            "RaceRank": 42,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "LeafFilter.com",
            "StartPosition": 40,
            "TimesPassed": 10,
            "SFDelta": -1,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Blake Koch(i)",
                "HistoricalDriverID": 3917,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -5042,
            "FirstName": "Blake",
            "HistoricalID": 3917,
            "IsInChase": false,
            "LastName": "Koch",
            "MembershipID": 165503,
            "Points": 0,
            "PointsPosition": 67,
            "RunningPositionPoints": 0,
            "is_on_track": true
        },
                {
            "AverageRestartSpeed": 151.899,
            "AverageRunningPosition": 41.222,
            "AverageSpeed": 126.054,
            "BestLap": 2,
            "BestSpeed": 169.189,
            "BestTime": 31.917,
            "CarMake": "Chv",
            "CarNo": "7",
            "ElapsedTime": 1074,
            "FastestLaps": 0,
            "LapCount": 25,
            "LapsLed": [],
            "LastLapSpeed": 158.721,
            "LastLapTime": 34.022,
            "Passes": 10,
            "PassingDifferential": 7,
            "RaceRank": 43,
            "ResultID": 0,
            "ResultStatus": 1,
            "Sponsor": "Pilot/Flying J",
            "StartPosition": 39,
            "TimesPassed": 3,
            "SFDelta": -2,
            "QualifyingStatus": 0,
            "Driver":             {
                "DriverName": "Michael Annett #",
                "HistoricalDriverID": 3861,
                "IsInChase": false
            },
            "BonusPoints": 0,
            "DeltaLeader": -4519,
            "FirstName": "Michael",
            "HistoricalID": 3861,
            "IsInChase": false,
            "LastName": "Annett",
            "MembershipID": 146574,
            "Points": 523,
            "PointsPosition": 33,
            "RunningPositionPoints": 1,
            "is_on_track": true
        }
    ],
    "BestLapTime": 30.627,
    "weatherInfo":     {
        "icon": "clear",
        "temp_f": 80.7,
        "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
        "weather": "Clear",
        "forecast_url": "http://www.wunderground.com/US/FL/Homestead.html",
        "ob_url": "http://www.wunderground.com/cgi-bin/findweather/getForecast?query=25.468384,-80.518715",
        "history_url": "http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KFLHOMES5"
    },
    "NumberOfCautionSegments": 1,
    "NumberOfCautions": 3,
    "NumberOfLeadChanges": 4,
    "NumberOfLeaders": 4
}
     * */
}
