//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nascar.WinApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nascar.WinApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;lap_number&quot;:8,&quot;elapsed_time&quot;:3076.0,&quot;flag_state&quot;:9,&quot;race_id&quot;:4315,&quot;laps_in_race&quot;:999,&quot;laps_to_go&quot;:991,&quot;vehicles&quot;:[{&quot;average_restart_speed&quot;:0.0,&quot;average_running_position&quot;:0.0,&quot;average_speed&quot;:176.431,&quot;best_lap&quot;:3,&quot;best_lap_speed&quot;:187.964,&quot;best_lap_time&quot;:50.946,&quot;vehicle_manufacturer&quot;:&quot;Frd&quot;,&quot;vehicle_number&quot;:&quot;16&quot;,&quot;driver&quot;:{&quot;driver_id&quot;:243,&quot;full_name&quot;:&quot;Greg Biffle&quot;,&quot;first_name&quot;:&quot;Greg&quot;,&quot;last_name&quot;:&quot;Biffle&quot;,&quot;is_in_chase&quot;:false},&quot;vehicle_elapsed_time&quot;:326.7078,&quot;fastest_laps_run&quot;:0,&quot;laps_completed&quot;:5,&quot;laps_led&quot;:[], [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cup_live_feed {
            get {
                return ResourceManager.GetString("cup_live_feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;lap_number&quot;:334,&quot;elapsed_time&quot;:12596.0,&quot;flag_state&quot;:9,&quot;race_id&quot;:4314,&quot;laps_in_race&quot;:334,&quot;laps_to_go&quot;:0,&quot;vehicles&quot;:[{&quot;average_restart_speed&quot;:176.205,&quot;average_running_position&quot;:31.458,&quot;average_speed&quot;:159.718,&quot;best_lap&quot;:5,&quot;best_lap_speed&quot;:187.963,&quot;best_lap_time&quot;:28.729,&quot;vehicle_manufacturer&quot;:&quot;Chv&quot;,&quot;vehicle_number&quot;:&quot;27&quot;,&quot;driver&quot;:{&quot;driver_id&quot;:2225,&quot;full_name&quot;:&quot;Paul Menard&quot;,&quot;first_name&quot;:&quot;Paul&quot;,&quot;last_name&quot;:&quot;Menard&quot;,&quot;is_in_chase&quot;:false},&quot;vehicle_elapsed_time&quot;:4573.283,&quot;fastest_laps_run&quot;:6,&quot;laps_completed&quot;:134,&quot;la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string live_feed_char_cup_final {
            get {
                return ResourceManager.GetString("live_feed_char_cup_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;lap_number&quot;:0,&quot;flag_state&quot;:8,&quot;elapsed_time&quot;:0.0,&quot;comment&quot;:&quot;&quot;,&quot;beneficiary&quot;:&quot;&quot;,&quot;time_of_day&quot;:0.0},{&quot;lap_number&quot;:0,&quot;flag_state&quot;:8,&quot;elapsed_time&quot;:0.0,&quot;comment&quot;:&quot;&quot;,&quot;beneficiary&quot;:&quot;&quot;,&quot;time_of_day&quot;:0.0},{&quot;lap_number&quot;:0,&quot;flag_state&quot;:1,&quot;elapsed_time&quot;:0.0,&quot;comment&quot;:&quot;&quot;,&quot;beneficiary&quot;:&quot;&quot;,&quot;time_of_day&quot;:0.0},{&quot;lap_number&quot;:59,&quot;flag_state&quot;:2,&quot;elapsed_time&quot;:2995.615,&quot;comment&quot;:&quot;#22, 1, 2, 4, 95, 18 Accident Frontstretch&quot;,&quot;beneficiary&quot;:&quot;98&quot;,&quot;time_of_day&quot;:0.0},{&quot;lap_number&quot;:64,&quot;flag_state&quot;:1,&quot;elapsed_time&quot;:3596.187,&quot;comment&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string live_flag_cup_tally_final {
            get {
                return ResourceManager.GetString("live_flag_cup_tally_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;bonus_points&quot;:0,&quot;car_number&quot;:&quot;22&quot;,&quot;delta_leader&quot;:0,&quot;delta_next&quot;:0,&quot;first_name&quot;:&quot;Joey&quot;,&quot;driver_id&quot;:3859,&quot;is_in_chase&quot;:true,&quot;last_name&quot;:&quot;Logano&quot;,&quot;membership_id&quot;:151509,&quot;points&quot;:3121,&quot;points_position&quot;:1,&quot;points_earned_this_race&quot;:33,&quot;wins&quot;:1,&quot;top_5&quot;:2,&quot;top_10&quot;:2,&quot;poles&quot;:1},{&quot;bonus_points&quot;:0,&quot;car_number&quot;:&quot;18&quot;,&quot;delta_leader&quot;:-35,&quot;delta_next&quot;:-4,&quot;first_name&quot;:&quot;Kyle&quot;,&quot;driver_id&quot;:454,&quot;is_in_chase&quot;:true,&quot;last_name&quot;:&quot;Busch&quot;,&quot;membership_id&quot;:85071,&quot;points&quot;:3086,&quot;points_position&quot;:9,&quot;points_earned_this_race&quot;:4,&quot;wins&quot;:0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string live_points_cup_tally_final {
            get {
                return ResourceManager.GetString("live_points_cup_tally_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;race_id&quot;:4315,&quot;series_id&quot;:1,&quot;qualifying_results&quot;:[{&quot;run_id&quot;:8,&quot;series_id&quot;:1,&quot;qualifying_round&quot;:1,&quot;position&quot;:11,&quot;vehicle_number&quot;:&quot;47&quot;,&quot;driver_id&quot;:3774,&quot;full_name&quot;:&quot;AJ Allmendinger&quot;,&quot;laps_completed&quot;:3,&quot;best_lap&quot;:3,&quot;best_lap_time&quot;:49.04,&quot;best_lap_speed&quot;:195.269,&quot;comment&quot;:&quot;&quot;,&quot;is_on_track&quot;:false,&quot;is_current_round&quot;:false,&quot;time_limit&quot;:657,&quot;last_lap_time&quot;:49.04},{&quot;run_id&quot;:9,&quot;series_id&quot;:1,&quot;qualifying_round&quot;:2,&quot;position&quot;:9,&quot;vehicle_number&quot;:&quot;47&quot;,&quot;driver_id&quot;:3774,&quot;full_name&quot;:&quot;AJ Allmendinger&quot;,&quot;laps_completed&quot;:3,&quot;best [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string live_qualifying_tally {
            get {
                return ResourceManager.GetString("live_qualifying_tally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;lap_number&quot;:194,&quot;elapsed_time&quot;:11900.0,&quot;flag_state&quot;:9,&quot;race_id&quot;:4315,&quot;laps_in_race&quot;:194,&quot;laps_to_go&quot;:0,&quot;vehicles&quot;:[{&quot;average_restart_speed&quot;:185.534,&quot;average_running_position&quot;:28.451,&quot;average_speed&quot;:160.281,&quot;best_lap&quot;:38,&quot;best_lap_speed&quot;:199.996,&quot;best_lap_time&quot;:47.881,&quot;vehicle_manufacturer&quot;:&quot;Tyt&quot;,&quot;vehicle_number&quot;:&quot;55&quot;,&quot;driver&quot;:{&quot;driver_id&quot;:3425,&quot;full_name&quot;:&quot;Brian Vickers&quot;,&quot;first_name&quot;:&quot;Brian&quot;,&quot;last_name&quot;:&quot;Vickers&quot;,&quot;is_in_chase&quot;:false},&quot;vehicle_elapsed_time&quot;:11752.8465,&quot;fastest_laps_run&quot;:3,&quot;laps_completed&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tally_final_cup_live_feed {
            get {
                return ResourceManager.GetString("tally_final_cup_live_feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;lap_number&quot;:95,&quot;elapsed_time&quot;:7094.0,&quot;flag_state&quot;:9,&quot;race_id&quot;:4371,&quot;laps_in_race&quot;:95,&quot;laps_to_go&quot;:0,&quot;vehicles&quot;:[{&quot;average_restart_speed&quot;:181.355,&quot;average_running_position&quot;:13.758,&quot;average_speed&quot;:132.621,&quot;best_lap&quot;:64,&quot;best_lap_speed&quot;:187.813,&quot;best_lap_time&quot;:50.987,&quot;vehicle_manufacturer&quot;:&quot;Frd&quot;,&quot;vehicle_number&quot;:&quot;19&quot;,&quot;driver&quot;:{&quot;driver_id&quot;:4065,&quot;full_name&quot;:&quot;Tyler Reddick #&quot;,&quot;first_name&quot;:&quot;Tyler&quot;,&quot;last_name&quot;:&quot;Reddick #&quot;,&quot;is_in_chase&quot;:false},&quot;vehicle_elapsed_time&quot;:6939.1424,&quot;fastest_laps_run&quot;:1,&quot;laps_completed&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string truck_live_feed_tally_final {
            get {
                return ResourceManager.GetString("truck_live_feed_tally_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;version&quot;:&quot;0.1&quot;,&quot;termsofService&quot;:&quot;http://www.wunderground.com/weather/api/d/terms.html&quot;,&quot;features&quot;:{&quot;conditions&quot;:1}},&quot;current_observation&quot;:{&quot;image&quot;:{&quot;url&quot;:&quot;http://icons.wxug.com/graphics/wu2/logo_130x80.png&quot;,&quot;title&quot;:&quot;Weather Underground&quot;,&quot;link&quot;:&quot;http://www.wunderground.com&quot;},&quot;display_location&quot;:{&quot;full&quot;:&quot;Talladega, AL&quot;,&quot;city&quot;:&quot;Talladega&quot;,&quot;state&quot;:&quot;AL&quot;,&quot;state_name&quot;:&quot;Alabama&quot;,&quot;country&quot;:&quot;US&quot;,&quot;country_iso3166&quot;:&quot;US&quot;,&quot;zip&quot;:&quot;35160&quot;,&quot;magic&quot;:&quot;1&quot;,&quot;wmo&quot;:&quot;99999&quot;,&quot;latitude&quot;:&quot;33.43900681&quot;,&quot;longitude&quot;:&quot;-86.10092 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string weather_underground_cup_tally_final {
            get {
                return ResourceManager.GetString("weather_underground_cup_tally_final", resourceCulture);
            }
        }
    }
}
