// <auto-generated />
namespace Nascar.Data.Schedule
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class wip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wip));
        
        string IMigrationMetadata.Id
        {
            get { return "201411071629595_wip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
